services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: chatbot-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ChatBot123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - chatbot-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatbot-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=ChatBotDb;User Id=sa;Password=ChatBot123!;Encrypt=False;TrustServerCertificate=True;
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver
    networks:
      - chatbot-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatbot-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - chatbot-network
    restart: unless-stopped

volumes:
  sqlserver_data:

networks:
  chatbot-network:
    driver: bridge
